-- ============================================================
-- boards 테이블에 숫자 방 번호(public_id) 추가
-- - 기존 UUID id는 그대로 유지 (실시간 채팅/공유/내부 참조 안정)
-- - 사용자는 public_id (예: 123)로 직통 입장 가능
-- Supabase SQL Editor에서 실행.
-- ============================================================

-- 1) public_id 컬럼 추가 (자동 증가, 고유)
ALTER TABLE public.boards
  ADD COLUMN IF NOT EXISTS public_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- 2) 기존 행에 public_id가 비어 있으면 채우기
-- (IDENTITY는 자동으로 채워지지 않으므로, null인 행만 업데이트)
UPDATE public.boards
  SET public_id = nextval(pg_get_serial_sequence('public.boards', 'public_id'))
  WHERE public_id IS NULL;

-- 3) 유니크 제약 (중복 방지)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'boards_public_id_unique'
  ) THEN
    ALTER TABLE public.boards
      ADD CONSTRAINT boards_public_id_unique UNIQUE (public_id);
  END IF;
END $$;

COMMENT ON COLUMN public.boards.public_id IS '사용자용 숫자 방 번호 (직통 입장용).';

